language: node_js
node_js:
  - '8.9'

branches:
  only:
    - develop
    - master

notifications:
  email:
    recipients:
      - j.bernal@upm.es

script:
  - npm install
  - npm run build --prod


