language: node_js
node_js:
  - '8.9'

branches:
  only:
    - develop
    - master

notifications:
  email:
    recipients:
      - j.bernal@upm.es

script:
  - npm install -g @angular/cli
  - npm install
  - ng build --prod

# Deploy https://fenw-angular-demo.herokuapp.com
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master
